services:
  - type: web
    name: la-ban-tuoi-teen
    env: node
    region: oregon
    plan: starter
    buildCommand: bash build.sh
    startCommand: cd backend && node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://postgres:Kawaiioo%40%23113@db.ozddlqdmkmhxhamvjgla.supabase.co:6543/postgres?pgbouncer=true
      - key: JWT_EXPIRES_IN
        value: 7d
